In [1]:
import numpy as np
import pandas as pd

In [4]:
races = pd.read_csv("races.csv")
results = pd.read_csv("results.csv")
drivers = pd.read_csv("drivers.csv")
constructors = pd.read_csv("constructors.csv")
circuits = pd.read_csv("circuits.csv")
qualifying = pd.read_csv("qualifying.csv")

# **Inspecting DataSet**

> **Inspecting Races Dataset**

In [12]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [8]:
races.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   object
 5   date         1125 non-null   object
 6   time         1125 non-null   object
 7   url          1125 non-null   object
 8   fp1_date     1125 non-null   object
 9   fp1_time     1125 non-null   object
 10  fp2_date     1125 non-null   object
 11  fp2_time     1125 non-null   object
 12  fp3_date     1125 non-null   object
 13  fp3_time     1125 non-null   object
 14  quali_date   1125 non-null   object
 15  quali_time   1125 non-null   object
 16  sprint_date  1125 non-null   object
 17  sprint_time  1125 non-null   object
dtypes: int64(4), object(14)
memory usage: 158.3+ KB

In [9]:
races.describe()

            raceId         year        round    circuitId
count  1125.000000  1125.000000  1125.000000  1125.000000
mean    565.710222  1992.703111     8.579556    23.889778
std     328.813817    20.603848     5.159910    19.633527
min       1.000000  1950.000000     1.000000     1.000000
25%     282.000000  1977.000000     4.000000     9.000000
50%     563.000000  1994.000000     8.000000    18.000000
75%     845.000000  2011.000000    13.000000    34.000000
max    1144.000000  2024.000000    24.000000    80.000000

In [10]:
races.shape

(1125, 18)

In [11]:
races.columns

Index(['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'time', 'url',
       'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time',
       'quali_date', 'quali_time', 'sprint_date', 'sprint_time'],
      dtype='object')

> **Inspecting Results Dataset**

In [13]:
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [14]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26759 non-null  int64
 1   raceId           26759 non-null  int64
 2   driverId         26759 non-null  int64
 3   constructorId    26759 non-null  int64
 4   number           26759 non-null  object
 5   grid             26759 non-null  int64
 6   position         26759 non-null  object
 7   positionText     26759 non-null  object
 8   positionOrder    26759 non-null  int64
 9   points           26759 non-null  float64
 10  laps             26759 non-null  int64
 11  time             26759 non-null  object
 12  milliseconds     26759 non-null  object
 13  fastestLap       26759 non-null  object
 14  rank             26759 non-null  object
 15  fastestLapTime   26759 non-null  object
 16  fastestLapSpeed  26759 non-null  object
 17  statusId         26759 non-null  int64
dtypes: float64(1), int64(8), object(9)
memory usage: 3.7+ MB

In [15]:
results.describe()

,resultId,raceId,driverId,constructorId,grid,positionOrder,points,laps,statusId
count,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000
mean,13380.977391,551.687283,278.673530,50.180537,11.134796,12.794051,1.987632,46.301768,17.224971
std,7726.134642,313.265036,282.703039,61.551498,7.202860,7.665951,4.351209,29.496557,26.026104
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,6690.500000,300.000000,57.000000,6.000000,5.000000,6.000000,0.000000,23.000000,1.000000
50%,13380.000000,531.000000,172.000000,25.000000,11.000000,12.000000,0.000000,53.000000,10.000000
75%,20069.500000,811.000000,399.500000,63.000000,17.000000,18.000000,2.000000,66.000000,14.000000
max,26764.000000,1144.000000,862.000000,215.000000,34.000000,39.000000,50.000000,200.000000,141.000000

In [16]:
results.shape

(26759, 18)

In [17]:
results.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId'],
      dtype='object')

> **Inspecting Drivers Dataset**

In [18]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [19]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     861 non-null    int64
 1   driverRef    861 non-null    object
 2   number       861 non-null    object
 3   code         861 non-null    object
 4   forename     861 non-null    object
 5   surname      861 non-null    object
 6   dob          861 non-null    object
 7   nationality  861 non-null    object
 8   url          861 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.7+ KB

In [20]:
drivers.describe()

         driverId
count  861.000000
mean   431.061556
std    248.793797
min      1.000000
25%    216.000000
50%    431.000000
75%    646.000000
max    862.000000

In [21]:
drivers.shape

(861, 9)

In [22]:
drivers.columns

Index(['driverId', 'driverRef', 'number', 'code', 'forename', 'surname', 'dob',
       'nationality', 'url'],
      dtype='object')

> **Inspecting Constructors Dataset**

In [23]:
constructors.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [24]:
constructors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   212 non-null    int64
 1   constructorRef  212 non-null    object
 2   name            212 non-null    object
 3   nationality     212 non-null    object
 4   url             212 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.4+ KB

In [25]:
constructors.describe()

       constructorId
count     212.000000
mean      107.547170
std        61.952685
min         1.000000
25%        54.750000
50%       107.500000
75%       160.250000
max       215.000000

In [26]:
constructors.shape

(212, 5)

In [27]:
constructors.columns

Index(['constructorId', 'constructorRef', 'name', 'nationality', 'url'], dtype='object')

> **Inspecting Circuits Dataset**

In [28]:
circuits.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

In [29]:
circuits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   circuitId   78 non-null     int64
 1   circuitRef  78 non-null     object
 2   name        78 non-null     object
 3   location    78 non-null     object
 4   country     78 non-null     object
 5   lat         78 non-null     float64
 6   lng         78 non-null     float64
 7   alt         78 non-null     int64
 8   url         78 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 5.6+ KB

In [30]:
circuits.describe()

       circuitId        lat         lng          alt
count  78.000000  78.000000   78.000000    78.000000
mean   40.410256  33.532955    1.016530   252.397436
std    23.321266  22.674218   65.092294   363.499347
min     1.000000 -37.849700 -118.189000    -7.000000
25%    20.250000  32.945025   -9.346393    18.250000
50%    40.500000  40.784400    3.547220   129.500000
75%    59.750000  46.935225   18.127625   341.750000
max    81.000000  57.265300  144.968000  2227.000000

In [31]:
circuits.shape

(78, 9)

In [32]:
circuits.columns

Index(['circuitId', 'circuitRef', 'name', 'location', 'country', 'lat', 'lng',
       'alt', 'url'],
      dtype='object')

> **Inspecting Qualifying Dataset**

In [33]:
qualifying.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [34]:
qualifying.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10494 entries, 0 to 10493
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      10494 non-null  int64
 1   raceId         10494 non-null  int64
 2   driverId       10494 non-null  int64
 3   constructorId  10494 non-null  int64
 4   number         10494 non-null  int64
 5   position       10494 non-null  int64
 6   q1             10494 non-null  object
 7   q2             10472 non-null  object
 8   q3             10448 non-null  object
dtypes: int64(6), object(3)
memory usage: 738.0+ KB

In [35]:
qualifying.describe()

,qualifyId,raceId,driverId,constructorId,number,position
count,10494.000000,10494.000000,10494.000000,10494.000000,10494.000000,10494.000000
mean,5262.482847,624.600915,343.002287,47.918430,18.786449,11.195826
std,3046.588486,428.298147,389.586448,73.217993,18.447502,6.260374
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
25%,2625.250000,160.000000,17.000000,4.000000,7.000000,6.000000
50%,5249.500000,870.000000,60.000000,9.000000,14.000000,11.000000
75%,7893.750000,1006.000000,822.000000,31.000000,22.000000,16.000000
max,10551.000000,1144.000000,862.000000,215.000000,99.000000,28.000000

In [36]:
qualifying.shape

(10494, 9)

In [37]:
qualifying.columns

Index(['qualifyId', 'raceId', 'driverId', 'constructorId', 'number',
       'position', 'q1', 'q2', 'q3'],
      dtype='object')

# **Checking for any Missing Values**

In [38]:
races.isnull().sum()

raceId         0
year           0
round          0
circuitId      0
name           0
date           0
time           0
url            0
fp1_date       0
fp1_time       0
fp2_date       0
fp2_time       0
fp3_date       0
fp3_time       0
quali_date     0
quali_time     0
sprint_date    0
sprint_time    0
dtype: int64

In [39]:
results.isnull().sum()

resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

In [40]:
drivers.isnull().sum()

driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64

In [41]:
constructors.isnull().sum()

constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

In [42]:
circuits.isnull().sum()

circuitId     0
circuitRef    0
name          0
location      0
country       0
lat           0
lng           0
alt           0
url           0
dtype: int64

In [43]:
qualifying.isnull().sum()

qualifyId         0
raceId            0
driverId          0
constructorId     0
number            0
position          0
q1                0
q2               22
q3               46
dtype: int64

> **Observations**

1. No duplicate records found.
2. No missing values in races, results, drivers, constructors, or circuits.
3. qualifying contains 22 missing values in q2 and 46 in q3.
4. These values were retained because they indicate drivers who did not progress to later qualifying sessions, making them valid missing values rather than data quality issues.

# **Merging DataSets**

In [44]:
master = results.copy()

In [46]:
#Merging Drivers Data

master = master.merge(
    drivers[['driverId', 'forename', 'surname']],
    on='driverId',
    how='left'
)

master['driver_name'] = master['forename'] + " " + master['surname']

master.drop(columns=['forename', 'surname'], inplace=True)

In [48]:
#Merging Constructors Data

master = master.merge(
    constructors[['constructorId', 'name']],
    on='constructorId',
    how='left'
)

master.rename(columns={'name': 'constructor'}, inplace=True)

In [49]:
#Merging Races Data

master = master.merge(
    races[['raceId', 'year', 'round', 'circuitId', 'name', 'date']],
    on='raceId',
    how='left'
)

master.rename(columns={'name': 'race_name'}, inplace=True)

In [50]:
#Merging Circuits Data

master = master.merge(
    circuits[['circuitId', 'name', 'location', 'country']],
    on='circuitId',
    how='left'
)

master.rename(columns={'name': 'circuit'}, inplace=True)

In [54]:
master.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,driver_name,constructor,year,round,circuitId,race_name,date,circuit,location,country
0,1,18,1,1,22,1,1,1,1,10.0,...,Lewis Hamilton,McLaren,2008,1,1,Australian Grand Prix,2008-03-16,Albert Park Grand Prix Circuit,Melbourne,Australia
1,2,18,2,2,3,5,2,2,2,8.0,...,Nick Heidfeld,BMW Sauber,2008,1,1,Australian Grand Prix,2008-03-16,Albert Park Grand Prix Circuit,Melbourne,Australia
2,3,18,3,3,7,7,3,3,3,6.0,...,Nico Rosberg,Williams,2008,1,1,Australian Grand Prix,2008-03-16,Albert Park Grand Prix Circuit,Melbourne,Australia
3,4,18,4,4,5,11,4,4,4,5.0,...,Fernando Alonso,Renault,2008,1,1,Australian Grand Prix,2008-03-16,Albert Park Grand Prix Circuit,Melbourne,Australia
4,5,18,5,1,23,3,5,5,5,4.0,...,Heikki Kovalainen,McLaren,2008,1,1,Australian Grand Prix,2008-03-16,Albert Park Grand Prix Circuit,Melbourne,Australia

In [53]:
master.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'driver_name', 'constructor', 'year',
       'round', 'circuitId', 'race_name', 'date', 'circuit', 'location',
       'country'],
      dtype='object')

# **Feature Engineering** (Adding Columns to make Analysis easier)

In [55]:
#Winner

master["winner"] = master["positionOrder"] == 1

In [56]:
#Podium Finish

master["podium"] = master["positionOrder"] <= 3

In [57]:
#Pole Position

master["pole_position"] = master["grid"] == 1

In [58]:
#Positions Gained

master["positions_gained"] = master["grid"] - master["positionOrder"]

In [59]:
#Finished Race

master["finished"] = master["statusId"] == 1

In [60]:
#Fastest Lap

master["fastest_lap"] = master["fastestLap"].notna()

In [61]:
#Speed

master["fastestLapSpeed"] = pd.to_numeric(
    master["fastestLapSpeed"],
    errors="coerce"
)

In [64]:
master["date"] = pd.to_datetime(master["date"])

In [66]:
master.isnull().sum()

resultId                0
raceId                  0
driverId                0
constructorId           0
number                  0
grid                    0
position                0
positionText            0
positionOrder           0
points                  0
laps                    0
time                    0
milliseconds            0
fastestLap              0
rank                    0
fastestLapTime          0
fastestLapSpeed     18507
statusId                0
driver_name             0
constructor             0
year                    0
round                   0
circuitId               0
race_name               0
date                    0
circuit                 0
location                0
country                 0
winner                  0
podium                  0
pole_position           0
positions_gained        0
finished                0
fastest_lap             0
dtype: int64

The **fastestLapSpeed** column contains a large number of missing values because speed data is unavailable for many historical races and retired drivers. Since these missing values represent unavailable information rather than errors, they were retained.

In [69]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   resultId          26759 non-null  int64
 1   raceId            26759 non-null  int64
 2   driverId          26759 non-null  int64
 3   constructorId     26759 non-null  int64
 4   number            26759 non-null  object
 5   grid              26759 non-null  int64
 6   position          26759 non-null  object
 7   positionText      26759 non-null  object
 8   positionOrder     26759 non-null  int64
 9   points            26759 non-null  float64
 10  laps              26759 non-null  int64
 11  time              26759 non-null  object
 12  milliseconds      26759 non-null  object
 13  fastestLap        26759 non-null  object
 14  rank              26759 non-null  object
 15  fastestLapTime    26759 non-null  object
 16  fastestLapSpeed   8252 non-null   float64
 17  statusId          26759 non-null  int64
 18  driver_name       26759 non-null  object
 19  constructor       26759 non-null  object
 20  year              26759 non-null  int64
 21  round             26759 non-null  int64
 22  circuitId         26759 non-null  int64
 23  race_name         26759 non-null  object
 24  date              26759 non-null  datetime64[ns]
 25  circuit           26759 non-null  object
 26  location          26759 non-null  object
 27  country           26759 non-null  object
 28  winner            26759 non-null  bool
 29  podium            26759 non-null  bool
 30  pole_position     26759 non-null  bool
 31  positions_gained  26759 non-null  int64
 32  finished          26759 non-null  bool
 33  fastest_lap       26759 non-null  bool
dtypes: bool(5), datetime64[ns](1), float64(2), int64(12), object(14)
memory usage: 6.0+ MB

In [71]:
master.to_csv("master_f1_dataset.csv", index=False)